name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22' # ou a versão que você está utilizando

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm run test

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Create .env file from secret
      run: |
        cat << 'EOF' > .env
        ${secrets.ENV_FILE}
        EOF
      shell: bash


    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v3
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/socialmarket-api:latest
        build-args:
          ENV_FILE=.env
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy SSH Key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to VPS
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << EOF
          # Login to Docker Hub
          echo "$DOCKER_PASSWORD" | sudo docker login -u "$DOCKER_USERNAME" --password-stdin

          # Stop and remove the existing container if it exists
          sudo docker stop socialmarket-api || true
          sudo docker rm socialmarket-api || true

          # Remove the existing image if it exists
          sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/socialmarket-api:latest || true

          # Pull the new image
          sudo docker pull ${{ secrets.DOCKER_USERNAME }}/socialmarket-api:latest

          # Run the new container
          sudo docker run --name socialmarket-api --env-file .env -d -p 3000:3000 ${{ secrets.DOCKER_USERNAME }}/socialmarket-api:latest

          # Logout from Docker Hub
          sudo docker logout
        EOF
